name: CI Workflow

on: 
  push:
    branches:
      - main


jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      # Descargar el código
      - name: Checkout code
        uses: actions/checkout@v4

      # Instalar pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Ejecutar tests con pytest
      - name: Run tests
        run: pytest test.py
